### ISSUE TITLE
node-gyp fails x509 build in node v10.2

### ISSUE THREAD

**Issue by csarven** [solid/node-solid-server#676]
On node-solid-server ff53c5c5f95fc36c7a11a3333567019fadf58a63 (4.0.9), node-gyp (3.6.2) appears to fail the x509 build if node v10.2 (probably 10.x)

See:

```
$ npm install                                                                                                          [43/45]
                                                                                                                                                                        
> x509@0.3.2 install /var/www/node-solid-server/node_modules/x509                                                                                                       
> node-gyp rebuild                                                                  
                                          
make: Entering directory '/var/www/node-solid-server/node_modules/x509/build'       
  CXX(target) Release/obj.target/x509/src/addon.o
In file included from ../include/addon.h:4:0,
                 from ../src/addon.cc:4:                                            
/home/csarven/.node-gyp/10.2.0/include/node/node.h:53:10: fatal error: core.h: No such file or directory
 #include "core.h"  // NOLINT(build/include_order)
          ^~~~~~~~                        
compilation terminated.
x509.target.mk:102: recipe for target 'Release/obj.target/x509/src/addon.o' failed  
make: *** [Release/obj.target/x509/src/addon.o] Error 1                             
make: Leaving directory '/var/www/node-solid-server/node_modules/x509/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/csarven/.nvm/versions/node/v10.2.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Linux 4.13.0-43-generic                                             
gyp ERR! command "/home/csarven/.nvm/versions/node/v10.2.0/bin/node" "/home/csarven/.nvm/versions/node/v10.2.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.$
s" "rebuild"                                                                        
gyp ERR! cwd /var/www/node-solid-server/node_modules/x509
gyp ERR! node -v v10.2.0
gyp ERR! node-gyp -v v3.6.2                                                         
gyp ERR! not ok
                                                                                    
> spawn-sync@1.0.15 postinstall /var/www/node-solid-server/node_modules/spawn-sync
> node postinstall                                                                  
                                                                                    
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: x509@0.3.2 (node_modules/x509):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: x509@0.3.2 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

added 761 packages in 18.046s
```

node v9.11.1 (maybe v9.x and v8.x?) seems to work. See also https://github.com/Southern/node-x509/issues/68 (mentioned by @dmitrizagidulin )

**Comment by RubenVerborgh** [comment]
It's okay, this is an optional dependency.
